name: Pipeline

on: [push, pull_request]

jobs:
  Build-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Pipeline"
      - uses: action/checkout@v4
      - run: ls -R