name: Pipeline

on: [push, pull_request]

jobs:
  Build-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Pipeline"
      - uses: actions/checkout@v4
      
      - name: Install Dependencies 
        run: pip install -r requirements.txt

      - name: Run Validation Script
        run: scripts/validate.sh

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
      